// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZsX52jf18g3uMDTL8_6yPVgNtIYOvgOg',
    appId: '1:621735716048:android:57e1821df62f62037cead5',
    messagingSenderId: '621735716048',
    projectId: 'maiflashchat',
    storageBucket: 'maiflashchat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOQf7Roc3EFtMyXhW9LCSU-PjxhE8tP4U',
    appId: '1:621735716048:ios:c4845241925599647cead5',
    messagingSenderId: '621735716048',
    projectId: 'maiflashchat',
    storageBucket: 'maiflashchat.appspot.com',
    iosClientId: '621735716048-auptvcgkogpdn2saf2m8dsb127nu8q6j.apps.googleusercontent.com',
    iosBundleId: 'com.maiflashchat',
  );
}
