// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW1wl3gcCuHNKzhLMnAyouWz1khhu6bn4',
    appId: '1:642716254913:web:1ea6a8794189882c24ca40',
    messagingSenderId: '642716254913',
    projectId: 'maibrewcrew',
    authDomain: 'maibrewcrew.firebaseapp.com',
    storageBucket: 'maibrewcrew.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdGogTE_WEzmBI1MT2ofhvjsWI9HwQbbI',
    appId: '1:642716254913:android:12b3a6d89ee284d024ca40',
    messagingSenderId: '642716254913',
    projectId: 'maibrewcrew',
    storageBucket: 'maibrewcrew.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9MASZX4f9_d-CkUB5nM-pL7mnHg53Nkk',
    appId: '1:642716254913:ios:176d4f81f4c5201024ca40',
    messagingSenderId: '642716254913',
    projectId: 'maibrewcrew',
    storageBucket: 'maibrewcrew.appspot.com',
    iosClientId: '642716254913-qvqrgr0lqdg768tljq3o3em94kjqgnd3.apps.googleusercontent.com',
    iosBundleId: 'maibrewcrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9MASZX4f9_d-CkUB5nM-pL7mnHg53Nkk',
    appId: '1:642716254913:ios:278ebbaacedcd25124ca40',
    messagingSenderId: '642716254913',
    projectId: 'maibrewcrew',
    storageBucket: 'maibrewcrew.appspot.com',
    iosClientId: '642716254913-b58jr5h7brir0d0gfgrv16of4a6nj3ai.apps.googleusercontent.com',
    iosBundleId: 'maibrewcrewmacos',
  );
}
